apiVersion: v1
kind: Service
metadata:
  name: mysql-demo-pod
  namespace: nagpdemo
  labels:
    name: mysql-demo-pod
    app: mysql-k8s-deployment
spec:
  clusterIP: None
  selector:
    app: mysql-k8s-deployment
    name: mysql-demo-pod
  ports:
    - port: 3306
      targetPort: 3306
