apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    name: sql-configs
    app: mysql-k8s-deployment
  namespace: nagpdemo
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS`customers-db`;
    USE `customers-db`;
    CREATE TABLE IF NOT EXISTS `customer_accounts` (
      `id` int NOT NULL AUTO_INCREMENT,
      `first_name` varchar(255) NOT NULL,
      `last_name` varchar(255) NOT NULL,
      `email` varchar(255) NOT NULL UNIQUE,
      `phone_number` varchar(20) DEFAULT NULL,
      `address` varchar(255) DEFAULT NULL,
      `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
      `created_by` varchar(255) DEFAULT NULL,
      `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      `updated_by` varchar(255) DEFAULT NULL,
      PRIMARY KEY (`id`)
    );