apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: nagpdemo
spec:
  type: LoadBalancer
  selector:
    app: api-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
